# Site settings
title: Ivan Demchenko's blog
email: raqy.style@gmail.com
description: This is a personal blog of Ivan Demchenko
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://raqystyle.github.com" # the base hostname & protocol for your site
twitter_username: raqystyle
github_username:  raqystyle

# Build settings
markdown: kramdown
permalink: :title

host: 0.0.0.0
port: 5000

gems:
  - octopress-autoprefixer
