baseURL: https://ivan-demchenko.github.io/
languageCode: "en-us"
title: Ivan's blog
theme: PaperMod

params:
  ShowReadingTime: true
  editPost:
    URL: "https://github.com/ivan-demchenko/ivan-demchenko.github.io"
    Text: "Suggest Changes"
    appendFilePath: true
  homeInfoParams:
    Title: Welcome to my website!
    Content:
      My name is Ivan Demchenko. I am a software engineer. I use this space to share observations, insights and ideas related to my professional experience. Feel free to check out my other accounts as well.

  socialIcons:
    - name: LinkedIn
      url: https://www.linkedin.com/in/ivandemchenko/
    - name: GitHub
      url: https://github.com/ivan-demchenko
    - name: YouTube
      url: https://www.youtube.com/channel/UCGmXEOxGQqwgZQ57P4w4uvQ

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "static/icon.png"
    favicon16x16: "static/icon16.png"
    favicon32x32: "static/icon32.png"
    apple_touch_icon: "static/icon.png"
    safari_pinned_tab: "static/icon.png"

taxonomies:
  tag: tags

menu:
  main:
    - name: Blog
      url: /blog/
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: Bookmarks
      url: /bookmarks/
      weight: 4
    - name: CV
      url: /cv/
      weight: 5
