name: Build and Deploy my blog

on: [push]

jobs:
  deployment:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: master
          access-token: ${{ secrets.DEPLOY_KEY }}
